# Stage 1: Build Angular Application
FROM node:20.11.1 AS build

# Install gettext-base to have access to envsubst
RUN apt-get update && apt-get install -y nginx gettext-base

# Copy package.json and package-lock.json to install dependencies
COPY ./package.json ./package-lock.json ./
RUN npm install

WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install nodemon globally to allow the code be reloaded
RUN npm install -g nodemon

# From NGINX we can access throught ports 80 or 443 (HTTP or HTTPS)
EXPOSE 80 443 4200

# Start NGINX when the container start
CMD ["/bin/sh", "-c", "\
    envsubst '${SERVER_DOMAIN} ${BACKEND_API_URL} ${CERT_KEY} ${CERT_NAME} ${WEB_DEV_SERVER_URL}' \
    < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
    cat /etc/nginx/conf.d/default.conf && \
    nginx && npx nodemon --config nodemon.json"]