# Stage 1: Build Angular Application
FROM node:20.11.1 AS build

# Copy package.json and package-lock.json to install dependencies
COPY ./package.json ./package-lock.json ./
RUN npm install

WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install nodemon globally to allow the code be reloaded
RUN npm install -g nodemon

# Expose HTTP (4200) and HTTPS (4201)
EXPOSE 4200
EXPOSE 4201

# Start nodemon
CMD npx nodemon